version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - 4409:9000
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - "sonarqube-conf:/opt/sonarqube/conf"
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql-data:/var/lib/postgresql/data"

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube-conf: {}
  sonarqube-data: {}
  sonarqube-extensions: {}
  postgresql: {}
  postgresql-data: {}
