version: "2"

services:
  sonarqube:
    image: sonarqube:latest
    volumes:
      - "sonarqube-data:/opt/sonarqube"
    ports:
      - 4409:9000
    environment:
      sonar.jdbc.url: jdbc:postgresql://localhost:4417/sonar?currentSchema=sonar
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar

volumes:
  sonarqube-data: {}
