version: "2"

services:
  sonarqube:
    image: sonarqube:latest
    volumes:
      - "sonarqube-conf:/opt/sonarqube/conf"
      - "sonarqube-data:/opt/sonarqube/data"
      - "sonarqube-extensions:/opt/sonarqube/extensions"
    ports:
      - 4409:9000
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    networks:
      - sonarnet

  db:
    image: postgres
    volumes:
      - "postgresql:/var/lib/postgresql"
      - "postgresql-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube-conf: {}
  sonarqube-data: {}
  sonarqube-extensions: {}
  postgresql: {}
  postgresql-data: {}
