version: "3.7"

services:
  registry:
    container_name: registry
    image: registry:latest
    ports:
      - 4424:5000
    volumes:
      - "registry-data:/var/lib/registry"

volumes:
  registry-data: {}
