version: "3.7"

services:
  ucd-server:
    container_name: ucds
    image: ibmcom/ucds:latest
    environment:
      LICENSE: accept
    ports:
      - 4416:8443
      - 4417:7918
    volumes:
      - "ucds-data:/opt/ibm-ucd/server"
      
  ucd-agent:
    container_name: ucda
    image: ibmcom/ucda:latest
    environment:
      AGENT_NAME: agent-docker
    volumes:
      - "ucda-data:/opt/ibm-ucd/agent"
    depends_on:
      - ucd-server

volumes:
  ucds-data: {}
  ucda-data: {}
