version: "3.7"

services:
  redmine:
    container_name: redmine
    image: redmine:latest
    environment:
      REDMINE_DB_MYSQL: localhost
      REDMINE_DB_PORT: 3306
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    ports:
      - 4406:3000
    volumes:
      - "redmine-data:/home/redmine/data"

volumes:
  redmine-data: {}
