version: "3.7"

services:
  scmmanager:
    container_name: scmmanager
    image: sdorra/scm-manager:latest
    ports:
     - 4419:8080
    volumes:
      - "scmm-lib:/var/lib/scm"
      - "scmm-data:/opt/scm-server"

volumes:
  scmm-lib: {}
  scmm-data: {}
