version: "3.7"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    ports:
      - 4404:3000
      - 22:22
    volumes:
      - "gitea-data:/data"

volumes:
  gitea-data: {}
