version: "3.7"

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: cloud
      MYSQL_PASSWORD: cloud
      MYSQL_HOST: localhost:3306
    ports:
      - 4407:80
    volumes:
      - "nextcloud-data:/var/www/html"

volumes:
  nextcloud-data: {}
