version: "3.7"

services:
  liberty:
    container_name: liberty
    image: websphere-liberty:latest
    environment:
      LICENSE: accept
    ports:
      - 4410:9080
      - 4411:9443
    volumes:
      - "wlp:/opt/ibm/wlp"
      - "./server.xml:/opt/ibm/wlp/usr/servers/defaultServer/server.xml"

volumes:
  wlp: {}
