version: "2"

services:
  openliberty:
    image: open-liberty:kernel
    ports:
      - 4412:9080
      - 4413:9443
    volumes:
      - "ol:/opt/ol/wlp"
      - "./server.xml:/opt/ol/wlp/usr/servers/defaultServer/server.xml"

volumes:
  ol: {}
