version: "3.7"

services:
  db2:
    container_name: db2
    image: ibmcom/db2:latest
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: db2inst1
      DBNAME: testdb
      BLU: "true"
      SAMPLEDB: "true"
      PERSISTENT_HOME: "true"
      ARCHIVE_LOGS: "true"
      AUTOCONFIG: "true"
    ports:
      - 4422:50000
    volumes:
      - "dbv:/database"

volumes:
  dbv: {}
