#docker build -f Dockerfile_cmdline -t byob-cmd:latest .
#docker run -p 4428:8080 -ti byob-cmd:latest

FROM ubuntu:bionic

WORKDIR /app
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git python2.7 python-pip && \
    git clone https://github.com/malwaredllc/byob.git . && \
    rm -rf .github .gitattributes .gitignore .travis.yml LICENSE README.md

WORKDIR /app/byob
RUN python setup.py && \
    pip install colorama

EXPOSE 8080
ENTRYPOINT ["python", "server.py", "--port", "8080"]
