version: "2"

services:
  jenkins:
    image: jenkins/jenkins:latest
    volumes:
      - "jenkins-data:/var/jenkins_home"
    ports:
      - 4402:8080
      - 4403:8443
      - 50000:50000
    environment:
      JENKINS_HOST_HOME: jenkins-data
    labels:
      kompose.service.type: nodeport

volumes:
  jenkins-data: {}
