version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - 4425:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer-data:/data"

volumes:
  portainer-data: {}
