version: "3.7"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 4426:3306
    volumes:
      - "mysql-data:/var/lib/mysql"
      
volumes:
  mysql-data: {}
