version: "2"

services:
  wiki:
    image: requarks/wiki:latest
    volumes:
      - "wiki-data:/var/wiki/repo"
    ports:
      - 4405:3000
    environment:
      DB_TYPE: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijs
      DB_NAME: wiki

volumes:
  wiki-data: {}
