version: "3.7"

services:
  wiki:
    container_name: wiki
    image: requarks/wiki:latest
    environment:
      DB_TYPE: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijs
      DB_NAME: wiki
    ports:
      - 4405:3000
    volumes:
      - "wiki-data:/var/wiki/repo"

volumes:
  wiki-data: {}
