version: "3.7"

services:
  was:
    container_name: was
    image: ibmcom/websphere-traditional:latest
    privileged: true
    environment:
      LICENSE: accept
    ports:
     - 4420:9043
     - 4421:9443
    volumes:
      - "was-data:/opt/IBM/WebSphere"
      - "was-tmp:/tmp"
      - "./PASSWORD:/tmp/PASSWORD"

volumes:
  was-data: {}
  was-tmp: {}
