version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresdb
    ports:
      - 4418:5432
    volumes:
      - "postgres-data:/var/lib/postgresql"

volumes:
  postgres-data: {}
